spring:
  application:
    name: purchase-post-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/buy_share
    username: postgres
    password: Buzzer@2025
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: purchase_service
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: true
    baseline-version: 0
    baseline-description: "Initial baseline"

# Azure Configuration
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=your-storage-account;AccountKey=your-account-key;EndpointSuffix=core.windows.net
    account-name: your-storage-account
    container: purchase-post-media
  servicebus:
    connection-string: Endpoint=sb://your-servicebus-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=your-shared-access-key
    queue-name: blob-upload-events

app:
  jwt:
    secret: mySecretKeyThatIsAtLeast32CharactersLongForJWTSecurity
    expiration: 86400

server:
  port: 8081

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:8080,http://localhost:8082
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  allow-credentials: true

# Logging
logging:
  level:
    com.app: DEBUG
    org.springframework.web: DEBUG
