spring:
  datasource:
    url: jdbc:h2:mem:purchase_post_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  s3:
    bucket: your-bucket-name
    sqsQueue: your-s3-event-queue-name

cloud:
  aws:
    region:
      static: us-east-1

server:
  port: 8080
